---
title: "Visualizing LIME Results"
author: "Shay Iyer"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(igraph)
library(tidygraph)
library(ggraph)
set_graph_style()
```

## run viewingdata.Rmd to load all datasets


```{r making event part of nodelist}

candidates <- c("BAZ2B", "CELF1", "FOXP1", "nrp2", "NRP2", "SRSF1", "YAP1")

SE <- read.csv("/Volumes/sheynkman/projects/shay_thesis/output/candidate_mapping/SE.csv") %>% filter(geneSymbol %in% candidates)
MXE <- read.csv("/Volumes/sheynkman/projects/shay_thesis/output/candidate_mapping/MXE.csv") %>% filter(geneSymbol %in% candidates)
A3SS <- read.csv("/Volumes/sheynkman/projects/shay_thesis/output/candidate_mapping/A3SS.csv") %>%  filter(geneSymbol %in% candidates)
A5SS <- read.csv("/Volumes/sheynkman/projects/shay_thesis/output/candidate_mapping/A5SS.csv") %>% filter(geneSymbol %in% candidates)

SE <- SE %>% select(c(GeneID, geneSymbol, chr, strand, PValue, FDR, IncLevel1, IncLevel2, IncLevelDifference, incID, excID)) %>% mutate("type" = "se")
MXE <- MXE %>% select(c(GeneID, geneSymbol, chr, strand, PValue, FDR, IncLevel1, IncLevel2, IncLevelDifference, incID, excID)) %>% mutate("type" = "mxe")
A3SS <- A3SS %>% select(c(GeneID, geneSymbol, chr, strand, PValue, FDR, IncLevel1, IncLevel2, IncLevelDifference, incID, excID)) %>% mutate("type" = "a3ss")
A5SS <- A5SS %>% select(c(GeneID, geneSymbol, chr, strand, PValue, FDR, IncLevel1, IncLevel2, IncLevelDifference, incID, excID))  %>% mutate("type" = "a5ss")

SE <- SE %>% 
  pivot_longer(
    cols = c(incID, excID), 
    names_to = "incOrExc",
    values_to = "specID"
  )  %>% select(-incOrExc)

MXE <- MXE %>% 
  pivot_longer(
    cols = c(incID, excID), 
    names_to = "incOrExc",
    values_to = "specID"
  ) %>% select(-incOrExc)

A3SS <- A3SS %>% 
  pivot_longer(
    cols = c(incID, excID), 
    names_to = "incOrExc",
    values_to = "specID"
  ) %>% select(-incOrExc)

A5SS <- A5SS %>% 
  pivot_longer(
    cols = c(incID, excID), 
    names_to = "incOrExc",
    values_to = "specID"
  ) %>% select(-incOrExc)

nodelist <- rbind(SE, MXE, A3SS, A5SS)
```

```{r making isoform part of Nodelist}
# nodelistcolumns <- c(GeneID, geneSymbol, chr, strand, PValue, FDR, IncLevel1, IncLevel2, IncLevelDifference, type, specID)

annot.baz2b <- rtracklayer::import("/Volumes/sheynkman/projects/shay_thesis/input-data/02_long-read-EC-WTC11-1_input/01_annotation/EC-BAZ2B.gtf") %>% as.data.frame()
annot.celf1 <- rtracklayer::import("/Volumes/sheynkman/projects/shay_thesis/input-data/02_long-read-EC-WTC11-1_input/01_annotation/EC-CELF1.gtf") %>% as.data.frame()
annot.foxp1 <- rtracklayer::import("/Volumes/sheynkman/projects/shay_thesis/input-data/02_long-read-EC-WTC11-1_input/01_annotation/EC-FOXP1.gtf") %>% as.data.frame()
annot.nrp1 <- rtracklayer::import("/Volumes/sheynkman/projects/shay_thesis/input-data/02_long-read-EC-WTC11-1_input/01_annotation/EC-NRP1.gtf") %>% as.data.frame()
annot.nrp2 <- rtracklayer::import("/Volumes/sheynkman/projects/shay_thesis/input-data/02_long-read-EC-WTC11-1_input/01_annotation/EC-NRP2.gtf") %>% as.data.frame()
annot.srsf1 <- rtracklayer::import("/Volumes/sheynkman/projects/shay_thesis/input-data/02_long-read-EC-WTC11-1_input/01_annotation/EC-SRSF1.gtf") %>% as.data.frame()
annot.yap1 <- rtracklayer::import("/Volumes/sheynkman/projects/shay_thesis/input-data/02_long-read-EC-WTC11-1_input/01_annotation/EC-YAP1.gtf") %>% as.data.frame()

annot.baz2b <- annot.baz2b %>% select(gene_id, gene_name, seqnames, strand, transcript_id) %>% rename( "GeneID" = gene_id, "geneSymbol" = gene_name, "chr" = seqnames, "specID" = transcript_id
) %>% add_column( "PValue" = NA, "FDR" = NA, "IncLevel1" = NA, "IncLevel2" = NA, "IncLevelDifference" = NA, "type" = "isoform") 

annot.celf1 <- annot.celf1 %>% select(gene_id, gene_name, seqnames, strand, transcript_id) %>% rename( "GeneID" = gene_id, "geneSymbol" = gene_name, "chr" = seqnames, "specID" = transcript_id
) %>% add_column( "PValue" = NA, "FDR" = NA, "IncLevel1" = NA, "IncLevel2" = NA, "IncLevelDifference" = NA, "type" = "isoform") 

annot.foxp1 <- annot.foxp1 %>% select(gene_id, gene_name, seqnames, strand, transcript_id) %>% rename( "GeneID" = gene_id, "geneSymbol" = gene_name, "chr" = seqnames, "specID" = transcript_id
) %>% add_column( "PValue" = NA, "FDR" = NA, "IncLevel1" = NA, "IncLevel2" = NA, "IncLevelDifference" = NA, "type" = "isoform") 

annot.nrp2 <- annot.nrp2 %>% select(gene_id, gene_name, seqnames, strand, transcript_id) %>% rename( "GeneID" = gene_id, "geneSymbol" = gene_name, "chr" = seqnames, "specID" = transcript_id
) %>% add_column( "PValue" = NA, "FDR" = NA, "IncLevel1" = NA, "IncLevel2" = NA, "IncLevelDifference" = NA, "type" = "isoform") 

annot.nrp2 <- annot.nrp2 %>% select(gene_id, gene_name, seqnames, strand, transcript_id) %>% rename( "GeneID" = gene_id, "geneSymbol" = gene_name, "chr" = seqnames, "specID" = transcript_id
) %>% add_column( "PValue" = NA, "FDR" = NA, "IncLevel1" = NA, "IncLevel2" = NA, "IncLevelDifference" = NA, "type" = "isoform") 

annot.srsf1 <- annot.srsf1 %>% select(gene_id, gene_name, seqnames, strand, transcript_id) %>% rename( "GeneID" = gene_id, "geneSymbol" = gene_name, "chr" = seqnames, "specID" = transcript_id
) %>% add_column( "PValue" = NA, "FDR" = NA, "IncLevel1" = NA, "IncLevel2" = NA, "IncLevelDifference" = NA, "type" = "isoform") 

annot.yap1 <- annot.yap1 %>% select(gene_id, gene_name, seqnames, strand, transcript_id) %>% rename( "GeneID" = gene_id, "geneSymbol" = gene_name, "chr" = seqnames, "specID" = transcript_id
) %>% add_column( "PValue" = NA, "FDR" = NA, "IncLevel1" = NA, "IncLevel2" = NA, "IncLevelDifference" = NA, "type" = "isoform")

fullnodelist <- rbind(nodelist, annot.baz2b, annot.celf1, annot.foxp1, annot.nrp2, annot.nrp2, annot.srsf1, annot.yap1)

```

```{r baz2b}
baz2b.edgelist <- baz2b.se %>% dplyr::select(eventID, transcript_id) %>% unique()
baz2b.edgelist <- as.matrix(baz2b.edgelist)
baz2b.g <- graph.edgelist(baz2b.edgelist, directed = T)
plot(baz2b.g, layout = layout_in_circle(baz2b.g), edge.arrow.size = 0.25, label.cex = 0.75, vertex.size = 10) + title(main = "BAZ2B interaction network")


V(baz2b.g)[degree(baz2b.g, mode = 'in') >= 5]
# ENST00000392783.6 ENST00000437839.5 
```

```{r celf1}
celf1.edgelist <- celf1.se %>% dplyr::select(eventID, transcript_id) %>% unique()
celf1.edgelist <- as.matrix(celf1.edgelist)
celf1.g <- graph.edgelist(celf1.edgelist, directed = T)
plot(celf1.g, layout = layout_in_circle(celf1.g), edge.arrow.size = 0.25, label.cex = 0.75, vertex.size = 10) + title(main = "CELF1 interaction network")

V(celf1.g)[degree(celf1.g, mode = 'in') >= 5]
```

```{r foxp1}

foxp1.all <- rbind(foxp1.se, foxp1.mxe)
foxp1.edgelist <- foxp1.all %>% dplyr::select(eventID, transcript_id) %>% unique()
foxp1.edgelist <- as.matrix(foxp1.edgelist)
foxp1.g <- graph.edgelist(foxp1.edgelist, directed = T)
plot(foxp1.g, layout = layout_in_circle(foxp1.g), edge.arrow.size = 0.25, label.cex = 0.75, vertex.size = 10) + title(main = "foxp1 interaction network")

V(foxp1.g)[degree(foxp1.g, mode = 'in') >= 5]
```

```{r nrp1}

nrp1.all <- rbind(nrp1.se, nrp1.mxe)
nrp1.edgelist <- nrp1.all %>% dplyr::select(eventID, transcript_id) %>% unique()
nrp1.edgelist <- as.matrix(nrp1.edgelist)
nrp1.g <- graph.edgelist(nrp1.edgelist, directed = T)
plot(nrp1.g, layout = layout_in_circle(nrp1.g), edge.arrow.size = 0.25, label.cex = 0.75, vertex.size = 10) + title(main = "nrp1 interaction network")

V(nrp1.g)[degree(nrp1.g, mode = 'in') >= 3]
```



```{r nrp2}

nrp2.all <- rbind(nrp2.se, nrp2.a5ss)
nrp2.edgelist <- nrp2.all %>% dplyr::select(eventID, transcript_id) %>% unique()
nrp2.edgelist <- as.matrix(nrp2.edgelist)
nrp2.g <- graph.edgelist(nrp2.edgelist, directed = T)
plot(nrp2.g, layout = layout_in_circle(nrp2.g), edge.arrow.size = 0.25, label.cex = 0.75, vertex.size = 10) + title(main = "nrp2 interaction network")

V(nrp2.g)[degree(nrp2.g, mode = 'in') >= 2]
```


```{r srsf1}

srsf1.edgelist <- srsf1.se %>% dplyr::select(eventID, transcript_id) %>% unique()
srsf1.edgelist <- as.matrix(srsf1.edgelist)
srsf1.g <- graph.edgelist(srsf1.edgelist, directed = T)
plot(srsf1.g, layout = layout_in_circle(srsf1.g), edge.arrow.size = 0.25, label.cex = 0.75, vertex.size = 10) + title(main = "srsf1 interaction network")

V(srsf1.g)[degree(srsf1.g, mode = 'in') >= 1]
```

```{r yap1}

yap1.edgelist <- yap1.se %>% dplyr::select(eventID, transcript_id) %>% unique()
yap1.edgelist <- as.matrix(yap1.edgelist)
yap1.g <- graph.edgelist(yap1.edgelist, directed = T)
plot(yap1.g, layout = layout_in_circle(yap1.g), edge.arrow.size = 0.25, label.cex = 0.75, vertex.size = 10) + title(main = "yap1 interaction network")

V(yap1.g)[degree(yap1.g, mode = 'in') >= 5]
```

```{r}
baz2b.se %>% filter(transcript_id == "ENST00000392783.6" | transcript_id == "ENST00000437839.5") %>% select(eventID, transcript_id) %>% unique()
```

```{r}

V(baz2b.g)[degree(baz2b.g, mode = 'out') == 1]

```

```{r}

annot.yap1 <- annot.yap1 %>% filter(geneSymbol == "YAP1")
annot.foxp1 <- annot.foxp1 %>% filter(geneSymbol == "FOXP1")
annot.nrp1 <- annot.nrp1 %>% filter(geneSymbol == "NRP1")
annot.nrp2 <- annot.nrp2 %>% filter(geneSymbol == "NRP2")
annot.baz2b <- annot.baz2b %>% filter(geneSymbol == "BAZ2B")
annot.celf1 <- annot.celf1 %>% filter(geneSymbol == "CELF1")
annot.srsf1 <- annot.srsf1 %>% filter(geneSymbol == "SRSF1")

rbind(annot.baz2b, annot.celf1, annot.foxp1, annot.nrp1, annot.nrp2, annot.srsf1, annot.yap1) %>% select(specID) %>% unique() %>% summarize(n = n()) 



isoform.stats <- rbind(annot.baz2b, annot.celf1, annot.foxp1, annot.nrp1, annot.nrp2, annot.srsf1, annot.yap1) %>% select(specID) %>% unique() %>% mutate("status" = ifelse(grepl("ENST", specID), "known", "novel")) %>% drop_na()

isoform.stats %>% group_by(status) %>% summarize(pct = (n()/(166+98)) * 100)

```

```{r}
master.maplist <- rbind(baz2b.se, celf1.se, foxp1.all, nrp1.all, nrp2.all, srsf1.se, yap1.a3ss, yap1.a5ss, yap1.mxe, yap1.se) %>% filter(gene_name %in% candidates) 

master.maplist %>% group_by(eventID) %>% summarize(n = n()) %>% nrow()
```

